Repository mindspore-lab/mindone, pull requests merged in 2024-03, with the labels that each got.

#399 SDXL: transpose `text_projection` in converting
  examples/stable_diffusion_xl/tools/model_conversion/convert_diffusers_to_mindone_sdxl.py
  examples/stable_diffusion_xl/tools/model_conversion/convert_weight.py
Labels: bug

#386 add SVD training support
  examples/stable_diffusion_v2/ldm/modules/train/trainer.py
  examples/stable_diffusion_xl/gm/helpers.py
  examples/stable_diffusion_xl/gm/modules/attention.py
  examples/stable_diffusion_xl/gm/modules/diffusionmodules/guiders.py
  examples/stable_diffusion_xl/gm/modules/diffusionmodules/loss.py
  examples/stable_diffusion_xl/gm/modules/diffusionmodules/openaimodel.py
  examples/stable_diffusion_xl/gm/modules/diffusionmodules/sigma_sampling.py
  examples/stable_diffusion_xl/gm/modules/distributions/distributions.py
  examples/stable_diffusion_xl/gm/modules/embedders/open_clip/tokenizer.py
  examples/stable_diffusion_xl/gm/modules/embedders/open_clip/transformer.py
  examples/svd/README.md
  examples/svd/configs/svd.yaml
  examples/svd/configs/svd_train.yaml
  examples/svd/configs/svd_xt.yaml
  examples/svd/data/__init__.py
  examples/svd/data/video_dataset.py
  examples/svd/image_to_video.py
  examples/svd/models/diffusion.py
  examples/svd/modules/diffusionmodules/guiders.py
  examples/svd/modules/diffusionmodules/sampler.py
  examples/svd/modules/diffusionmodules/util.py
  examples/svd/modules/encoders/modules.py
  examples/svd/modules/unet3d.py
  examples/svd/requirements.txt
  examples/svd/train.py
  examples/svd/utils.py
  mindone/data/video_reader.py
  mindone/trainers/optim.py
Labels: feature

#398 Add min-snr weighting to improve AD training && Support any-shape infer
  examples/animatediff/README.md
  examples/animatediff/ad/models/autoencoder.py
  examples/animatediff/ad/models/diffusion/ddpm.py
  examples/animatediff/ad/modules/attention.py
  examples/animatediff/ad/modules/diffusionmodules/openaimodel.py
  examples/animatediff/ad/modules/diffusionmodules/unet3d.py
  examples/animatediff/args_train.py
  examples/animatediff/configs/stable_diffusion/v1-inference-mmv1.yaml
  examples/animatediff/configs/stable_diffusion/v1-inference-mmv2.yaml
  examples/animatediff/configs/stable_diffusion/v1-train-mmv2.yaml
  examples/animatediff/configs/training/mmv2_finetune_512.yaml
  examples/animatediff/scripts/run_mmv2_finetune_512.sh
  examples/animatediff/scripts/run_mmv2_train_512_webvid5.sh
  examples/animatediff/scripts/run_mmv2_train_gpu.sh
  examples/animatediff/train.py
Labels: feature

#409 Latte training bug fix: temp_embed initialization
  mindone/models/latte.py
  mindone/models/modules/pos_embed.py
Labels: bug

#410 SDV2: fix sdv2 text_overfit bug
  examples/stable_diffusion_v2/tests/st/test_overfit.py
Labels: bug

#405 Training Pipeline for ControlNet + SDXL
  examples/stable_diffusion_xl/cldm/cldm.py
  examples/stable_diffusion_xl/cldm/util.py
  examples/stable_diffusion_xl/configs/inference/sd_xl_base_controlnet.yaml
  examples/stable_diffusion_xl/configs/training/sd_xl_base_finetune_controlnet_910b.yaml
  examples/stable_diffusion_xl/controlnet.md
  examples/stable_diffusion_xl/demo/sampling_without_streamlit.py
  examples/stable_diffusion_xl/gm/data/dataset.py
  examples/stable_diffusion_xl/gm/data/mappers/sample_mappers.py
  examples/stable_diffusion_xl/gm/helpers.py
  examples/stable_diffusion_xl/gm/models/trainer_factory.py
  examples/stable_diffusion_xl/scripts/run_infer_base_controlnet.sh
  examples/stable_diffusion_xl/scripts/run_train_base_controlnet.sh
  examples/stable_diffusion_xl/tools/controlnet_conversion/README.md
  examples/stable_diffusion_xl/tools/controlnet_conversion/init_weight.py
  examples/stable_diffusion_xl/train_controlnet.py
Labels: feature

#407 rename `MSVersion` to match PEP 8
  examples/animatediff/ad/modules/attention.py
  examples/svd/models/diffusion.py
  mindone/models/lora.py
  mindone/models/modules/flash_attention.py
  mindone/utils/version_control.py
Labels: refactor

#406 refactor mindone's dataloader
  examples/svd/train.py
  examples/t2i_adapter/train_t2i_adapter_sd.py
  mindone/data/__init__.py
  mindone/data/loader.py
Labels: refactor
